### ISSUE TITLE
Can't use strings with non ascii characters as msgid

### ISSUE THREAD

**Issue by lyakishev** [gmarty/xgettext#21]
Handlebars template containing translatable strings with non ascii characters:

```
...
{{_ "Строка"}}
...
```

Result PO file:

```
...
msgid "??????
...
```

Because charset is not passed to gt.po.compile method (https://github.com/gmarty/handlebars-xgettext/blob/master/lib/handlebars-xgettext.js#L69) and default charset in gettext-parser is iso-8859-1 (or it is gettext-parser's bug?)

**Comment by Ciantic** [comment]
I'm now having issue with non-ascii chars.

I have JS files parsed by poedit normally having äö chars and they work.

But as soon as I add "äö" chars in EJS files it won't work:

```
10.6.2016 7.32.23: C:\...\msgcat.exe: input file 'C:\...\POEDIT~1\poe89D9.tmp\13extracted.pot' doesn't contain a header entry with a charset specification
10.6.2016 7.32.23: Failed command: msgcat --force-po -o "C:\...\POEDIT~1\poe89D9.tmp\15merged.pot"  "C:\...\POEDIT~1\poe89D9.tmp\13extracted.pot" "C:\...\POEDIT~1\poe89D9.tmp\14extracted.pot"
10.6.2016 7.32.23: Failed to merge gettext catalogues.
```

I've checked the EJS template is UTF-8, the Catalogue Properties says UTF-8 and my settings are following

![image](https://cloud.githubusercontent.com/assets/64731/15954373/ee0f3eba-2ede-11e6-8009-1836403bf198.png)
