### ISSUE TITLE
I've forked and published some competing and complementary packages

### ISSUE THREAD

**Issue by dschissler** [gmarty/xgettext#37]
## github
* [xgettext](https://github.com/dschissler/xgettext)
* [gettext-volt](https://github.com/dschissler/gettext-volt)
* ~~[gettext-swig](https://github.com/dschissler/gettext-swig)~~ (Now using upstream) (I'm using Nunjucks now, but its the same)

## npm
* ~~xgettext-template-dschissler~~ [Use github for all]

The npm package xgettext-template-dschissler links to the github commits for the gettext-volt and gettext-swig packages.

I'll admit that my gettext-volt regexs are not super great but they do handle a variety of Volt uses that the xgettext-swig one doesn't consider.  I forked these since these uses are not valid for Swig and Nunjuck.

Here is my test [Volt](http://docs.phalconphp.com/en/latest/reference/volt.html) template to demonstrate the different types of uses.  My code is working against my larger code base.

```
{{ t('Single Quote.')}}
{{t("Double Quote.") }}

{{n("Singular.", "Plural", n) }}

{{ link_to('features/angular', this.translate.gettext('Angular'), 'class':'btn btn-primary') }}

{{ submit_button(t('Change Password'), "class": "btn btn-primary") }}

{{ link_to('signin', t('Signin')) }}

{{ link_to("admin/users/create", "<i class='glyphicon glyphicon-plus-sign'></i> " ~ t('Create User'), "class": "btn btn-primary pull-right") }}

```

**Comment by dschissler** [comment]
Ya.  So please merge this work.  Its kind of silly to have a package named xgettext-template-dschissler.

**Comment by sergeyklay** [comment]
+1

**Comment by smhg** [comment]
Thank you for your contributions.
As you might have seen, gettext-swig (updated in xgettext-template) now contains your suggestions.
I think it is best if we discuss **gettext-volt** further in its repo. I'll try to have a look at it shortly.
Lets keep this issue open for a possible future integration.

**Comment by dschissler** [comment]
@smhg Its been a long time and I'd like to get this included into xgettext-template.  Do you have any additional requirements?

**Comment by smhg** [comment]
@dschissler thanks for the followup. It's been a long time, but there seems to be one issue in the gettext-volt repo about Volt specific tests. Could you have a look at that first?

**Comment by dschissler** [comment]
@smhg I believe that I finished it. Please review [gettext-volt](https://github.com/perchlayer/gettext-volt) for inclusion into this project.

**Comment by smhg** [comment]
Version 2.3 includes the Volt parser and is on npm. Thank you!

**Comment by dschissler** [comment]
@smhg https://forum.phalconphp.com/discussion/9683/volt-gettext-parser-is-now-available-through-xgettexttemplate

If you see some version jumps in the near future it will just be better documentation.  I'll make sure to notify you when there are bug fixes and enhancements.
