### ISSUE TITLE
My attempt at a twig parser

### ISSUE THREAD

**Issue by amenadiel** [gmarty/xgettext#41]
I was frustrated that Twig's gettext extractor had to compile the twig templates as php files, so I adapter the gettext-swig package to parse twig templates.

It's just an experiment but it's already getting me through my use case which was very specific.

https://github.com/amenadiel/gettext-twig

**Comment by smhg** [comment]
Thank you for the effort.
Do you think you can get this up to a working level? I'd be happy to include it.
You'd need to include tests (you can use the ones from the swig parser).

As a general note: it would be great if you'd be able to build it on top of a general twig parser. Parsing with regex is prone to (future) errors.

**Comment by smhg** [comment]
I'm going to close this. Just open a new issue or PR when you're ready.

**Comment by amenadiel** [comment]
Ok. Thanks for your attention. 

I'll look for a node based twig parser, because the PHP ones rely in compiling twig to php before attempting to find gettext expressions, so the results fail to reference the template itself. 

Of course I'd include tests if I ever get this working.

Best regards!
