### ISSUE TITLE
Add charset to Content-Type header of PO output

### ISSUE THREAD

**Issue by Ciantic** [gmarty/xgettext#47]
I'm now having issue with non-ascii chars.

I have JS files parsed by poedit normally having äö chars and they work.

But as soon as I add "äö" chars in EJS files, and try to use Update from Sources it won't work:

```
10.6.2016 7.32.23: C:\...\msgcat.exe: input file 'C:\...\POEDIT~1\poe89D9.tmp\13extracted.pot' doesn't contain a header entry with a charset specification
10.6.2016 7.32.23: Failed command: msgcat --force-po -o "C:\...\POEDIT~1\poe89D9.tmp\15merged.pot"  "C:\...\POEDIT~1\poe89D9.tmp\13extracted.pot" "C:\...\POEDIT~1\poe89D9.tmp\14extracted.pot"
10.6.2016 7.32.23: Failed to merge gettext catalogues.
```

I've checked the EJS template is UTF-8, the Catalogue Properties says UTF-8 and my settings are following

![image](https://cloud.githubusercontent.com/assets/64731/15954373/ee0f3eba-2ede-11e6-8009-1836403bf198.png)

Having `--force-po` in there also doesn't seem to make a difference. If I remove `‪--from-code=%c` it works but the äö characters are not recgonized correctly.

**Comment by Ciantic** [comment]
Here is a quick patch, open index.js and find this

```
var po = gt.po.compile({
          charset: options['from-code'],
          translations: {
            '': context
          }
        });
```

Replace it with this:

```
var po = gt.po.compile({
          charset: options['from-code'],
          headers: { "content-type": "text/plain; charset=" + options['from-code'] },
          translations: {
            '': context
          }
        });
```

Looks like this plugin has either stopped working, or was never working with PoEdit's scan. It requires the header charset's to match.

**Comment by smhg** [comment]
Thanks for the report & fix.
I've had a look at the po compiler in `gettext-parser` that handles this. If I get it right, the charset is only added to the headers (if it is not set as a separate property)[https://github.com/andris9/gettext-parser/blob/v1.1.2/lib/pocompiler.js#L179].
In that case your solution seems fine (the charset property can be removed too).
Would you want to have a second look at what gettext-parser expects and send an appropriate PR? Please also bump to the latest version of gettext-parser.
