### ISSUE TITLE
Add support for -j (--join-existing) flag

### ISSUE THREAD

**Issue by ZiperRom1** [gmarty/xgettext#48]
When you run the command, the output replace the original .po contents.
An update would be must appreciated.
For example, basic use-case would be added a new template with new words to translate.
Then you run the command but all the translations already done before are erased in the new .po generated.

**Comment by smhg** [comment]
That would indeed need to be supported with the `-j` (`--join-existing`) flag. Feel free to send a PR.
Or you can use Poedit. That should merge with an existing file just fine.

**Comment by ZiperRom1** [comment]
Thanks for the quick answer, I may send a PR if this structure using xgettext in the translation process in my company will be used. We are currently testing some email templates structures.

**Comment by ZiperRom1** [comment]
I found a quick fix for this using another js lib [stonejs](https://github.com/flozz/stonejs-tools).
The steps are :
- 1st generate a unique .pot file using `xgettext-template -D templates -o locales/catalog.pot -L Handlebars`
- Then update your .po file per lang using `stonejs update locales/*.po locales/catalog.pot`

**Comment by smhg** [comment]
Nice solution!
I'll leave this issue open as a reference for future development.

**Comment by smhg** [comment]
Release 3.0.0 is available through **npm** and allows you to merge with existing files with the `-j` flag.
