### ISSUE TITLE
using {{n_ "text" "texts" count}} doesn't extract the data

### ISSUE THREAD

**Issue by tombertrand** [gmarty/xgettext#53]
Hey, I've been doing experiments and trying the plural form of words. I'm having difficulties to extract text using the `n_` shorthand suggested in the [gettext-handlebars](https://github.com/smhg/gettext-handlebars) while `ngettext` works as expected.

Result from `ngettext`
![screen shot 2016-07-13 at 10 59 32 am](https://cloud.githubusercontent.com/assets/19352322/16808118/26aec528-48e9-11e6-8889-688a11fc46ec.png)

On a side note, would it be possible to run the `xgettext-template` cmd using different helpers name? for example, I would like to use `{{l10n "text"}}` instead of `{{_ "text"}}`?

Thanks.

**Comment by smhg** [comment]
Your last question first: yes, you can specify your own keywords with the `--keyword` parameter.

Could you paste an example file for which plural forms are not being extracted?

**Comment by tombertrand** [comment]
I'm having this like in a .hbs template

```html
<h2>{{ngettext "Payment" "Payments" 3}}</h2> <!-- works -->
<h2>{{n_ "Payment" "Payments" 3}}</h2> <!-- no output for "payment" to be found inside the po file -->
```

**Comment by smhg** [comment]
If you run `xgettext-template --help` you see the default plural keyword is only `ngettext`.
You'll need to specify your own for this to work.

These options should do it:
`-k gettext -k _ -k ngettext:1,2 -k n_:1,2`

**Comment by tombertrand** [comment]
oh! thank you for the very quick reply

**Comment by tombertrand** [comment]
works like a charm
