### ISSUE TITLE
Did't work with Handlebars

### ISSUE THREAD

**Issue by Krukov** [gmarty/xgettext#54]
Hi, 

I don't know where the problem, at this package or at the https://github.com/smhg/gettext-handlebars, but after update at 3.0 version working with `.hbs` files I see nothing at output 

```bash 
root@6ece96c0ff1c:/app# npm list -g xgettext-template
npm info it worked if it ends with ok
npm info using npm@3.9.2
npm info using node@v4.4.5
/usr/local/lib
└── xgettext-template@3.0.0 

npm info ok 
root@6ece96c0ff1c:/app# xgettext-template -k t client-pos/pos_app/modules/layout/templates/layout.hbs 
root@6ece96c0ff1c:/app# npm i -g xgettext-template@2.6.1 >/dev/null 2>/dev/null 
root@6ece96c0ff1c:/app# xgettext-template -k t client-pos/pos_app/modules/layout/templates/layout.hbs 
msgid ""
msgstr "Content-Type: text/plain; charset=ascii\n"

#: client-pos/pos_app/modules/layout/templates/layout.hbs:19
msgid "POS"
msgstr ""

#: client-pos/pos_app/modules/layout/templates/layout.hbs:26
msgid "Salon desk"
msgstr ""

#: client-pos/pos_app/modules/layout/templates/layout.hbs:33
msgid "Salon page"
msgstr ""

#: client-pos/pos_app/modules/layout/templates/layout.hbs:71
msgid "Settings"
msgstr "" 
```

**Comment by smhg** [comment]
Version 3 has [a breaking change](https://github.com/gmarty/xgettext/releases/tag/v3.0.0) that aligns the output with "native" `xgettext`.
While previously default output went to stdout, it now goes to a default `messages.po` in the current directory.

If you want the old behaviour, you have to add `--output=-` (or `-o -`).
I'll add this to the README.

**Comment by Krukov** [comment]
Thanks you for quick reply and for your  work :+1:
