### ISSUE TITLE
New method pgettext() not recognizing by Poedit

### ISSUE THREAD

**Issue by Zaszczyk** [gmarty/xgettext#59]
I've implemented method pgettext() in my gettext adapter to handle context and I would like to Poedit recognize pgettext() in .volt files. I've added this keyword in Catalogoue->Properties->Keywords, it works for *.php file only, it doesn't work for *.volt.

Should I add something extra to extractor's settings or somewhere else?

**Comment by smhg** [comment]
You should also configure an extractor under _File - Preferences_.
You can see how that should look based on the example in the Readme.

**Comment by dschissler** [comment]
Try to base it on this [screenshot](https://camo.githubusercontent.com/82cd61bf43975c07e167b19cbd037df6e2da3d7f/687474703a2f2f676d617274792e6769746875622e696f2f78676574746578742f506f656469742e706e67).  Just change the description at the top to "Volt" and set the extensions to `*.volt`.  The `.po` file must be setup correctly with keywords and then this extractor setup is for the Poedit app.

Sorry I can could have helped earlier but I was very distracted since I was just getting the election result now.

**Comment by Zaszczyk** [comment]
@smhg @dschissler obviously I have configured extractor, because I use xgettext-volt from 6 months :) it's great lib! And I would like to add new keyword now. Extractor config:
![extractor](https://cloud.githubusercontent.com/assets/7737337/20157026/23bac8ba-a6d3-11e6-90c5-1f33313c3d86.png)
Keywords config:
![keywords](https://cloud.githubusercontent.com/assets/7737337/20157069/5d498526-a6d3-11e6-94c8-904ada55a08f.png)
And Poedit parses string:
`{{ translation.pgettext('general.merged', [], 'female') }}`
as normal translation._(), without context.
Details:
-general.merged - msgid
-[] - empty array with placeholders
-female - context

However when I put this pgettext translation to .php file, Poedit parses it right - with context.

**Comment by dschissler** [comment]
I'm not familiar with the `3c,1` modifier.  What is that?

**Comment by Zaszczyk** [comment]
It means: third argument is context and first argument is msgid. I've also tested "1c,2" and "1,2c" and it doesn't work.

**Comment by smhg** [comment]
I'll try to test your setup. Which versions of Poedit and xgettext-template are you using?

**Comment by Zaszczyk** [comment]
Poedit is 1.8.11 and xgettext-template is 3.2.0

**Comment by smhg** [comment]
How could I forget... only the Handlebars parser supports contexts currently.
You'll need to send a PR to [xgettext-volt](https://github.com/perchlayer/gettext-volt) or convince @dschissler to implement it ;)
You can use [xgettext-handlebars](https://github.com/smhg/gettext-handlebars) as a reference.

**Comment by dschissler** [comment]
I'll think that I can put some time into this within the next few weeks.

**Comment by Zaszczyk** [comment]
@dschissler I wil be very thankful! :)
