### ISSUE TITLE
Duplicate entries when using contexts.

### ISSUE THREAD

**Issue by eldarc** [gmarty/xgettext#61]
If contexts are used for messages, and at the same time the `--join-existing` parameter is used, duplicate entries will be added to the `.po` file.

This happens when saving to an already existing `.po` file.

**Comment by smhg** [comment]
I think I fixed it with 5ebd7e4b307c9f978d02035e15a01c40e6477450.
Could you please give this a try (master)?

I'll need to add a proper test for this, but I couldn't get that set up right away.

**Comment by eldarc** [comment]
It appears to be fixed. I tested it with the new Nunjucks parser and it works as expected.

Thank you.

**Comment by smhg** [comment]
Great to hear it works. Thanks!
