### ISSUE TITLE
Orphaned messages when using `--join-existing`

### ISSUE THREAD

**Issue by eldarc** [gmarty/xgettext#63]
Suppose source files contain following two messages:
`_('First message')`
`_('Second message')`

Those will be added to the .po file. Translators can translate them and translations will be saved and not overwritten when using `--join-existing`.

However, if the developer changed a message, for example `_('Second message')` to `_('Third message')` and  `_('Second message')` has now 0 occurrences in all source files, it should be removed from the .po file.

Currently, the `deepMerge` method merges all messages from the existing .po file. Before doing the merge, orphaned messages should be marked and ignored when merging or a direct check should be performed while merging.

**Comment by smhg** [comment]
xgettext seems to do the same. This is our reference, so I'd keep it like that.
One reason might be that this can be used by your translation software for future suggestions.

As a sidenote: poEdit offers a "Purge deleted translations" option that deletes these.
