### ISSUE TITLE
Default keyword spec not parser specific.

### ISSUE THREAD

**Issue by eldarc** [gmarty/xgettext#64]
When there are no custom keywords, only `_`, `gettext`, `ngettext` are parsed.

Wouldn't it be better to load default parser specific keywordSpec?

So, something like this:

In index.js:
`spec = options.keyword.length > 0 ? Keywordspec(options.keyword) : [],`

In bin/xgettext-template
`'keyword': [],`

**Comment by smhg** [comment]
Yes, that sounds like a good idea. [GNU's xgettext](https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/xgettext-Invocation.html) has a default per language too.
This could go in `Parser.keywordSpec`? With a fallback to old default until all parsers support this.

**Comment by eldarc** [comment]
I think that all parsers can parse if an undefined object is passed to the constructor. They all have something like this: ```var keywordSpec = customKeywordSpec || {
        _: [0],
        gettext: [0],
        ngettext: [0, 1]
};```

So, it should be fine if xgettext-template sets the keyword parameter default value to `[]`. If the parser receives an undefined object it will use its default `keywordSpec` object.

**Comment by smhg** [comment]
You never know, there might be unlisted parsers out there.
I'd like to break as little as possible. Things can always be removed in the next major version.
This means xgettext-template provides `['_', 'gettext', 'ngettext:1,2']` if the parser doesn't export a default keyword spec.

I think the goals should be:
* Parsers are responsible for their default keywords (which is the case).
* Parsers should export them.
* Although parsers might use them themselves already if no keywordSpec is provided, xgettext-template needs to feed them their own defaults. Something like `new Parser(keywordSpec || Parser.keywordSpec)`.
* The default keyword should be removed from the executable.

**Comment by eldarc** [comment]
Yes. This makes sense.

Are you going to do that for `gettext-handlebars` first? I can do it for `gettext-nunjucks`.

After that, adjustments for `xgettext-template`?

**Comment by smhg** [comment]
The default keywords are now [exposed](https://github.com/smhg/gettext-handlebars/commit/7b1db70eceeb05d39787e4f5337a9b48acf29265) in `gettext-handlebars`.
And they are also used in this project, so feel free to update `gettext-nunjucks` in a similar fashion.
