### ISSUE TITLE
Additional maintainer

### ISSUE THREAD

**Issue by smhg** [gmarty/xgettext#68]
@gmarty, would you be willing to add @eldarc as a maintainer both here and npm?
He made quite a few contributions and my lack of time is currently keeping him from publishing those.

Thanks!

**Comment by gmarty** [comment]
Hey, sorry I just noticed this issue.
I add @eldarc as an admin of this repo.

**Comment by gmarty** [comment]
And I added him as an owner on npm too.
@eldarc: can you please check that everything is OK on your side?
If so, please close this issue.

Thanks a lot for the great job! 👍

**Comment by eldarc** [comment]
@gmarty Everything 🆗 

Thank you 🙂
