### ISSUE TITLE
New release is out

### ISSUE THREAD

**Issue by eldarc** [gmarty/xgettext#70]
@smhg A lot of time has passed since I worked on improvements. And the dependency update for Nunjucks was getting really required. So I decided to make a release. It does seem stable, but please if you have any suspicions that something could be broken let me know.

**Comment by smhg** [comment]
Thanks!
Are you familiar with semver?
Please be sure to update the version digits according to the type of changes. Specifically: if there is the slightest possibility the update breaks something, it's a new major version.
I can't tell anymore if this was the case, but this requires some thought when you release.

But great to see this progress! Thanks!
