### ISSUE TITLE
How to parse multiple files?

### ISSUE THREAD

**Issue by chlab** [gmarty/xgettext#72]
Hi

Thanks for this tool! I'm trying to get it to parse all of my files. I can't get it to work with poedit but I'd prefer to use it from the cli anyway. I am able to parse one file like so:

```
xgettext-template -o locale/en/LC_MESSAGES/test.po -L Vue -D resources/js components/ProjectLookup.vue
```

But how can I parse the entire directory? Is that left to poedit?

Thanks.

**Comment by eldarc** [comment]
@chlab 

You could do something like this:
`find ./src/components -name "*.vue" | xargs xgettext-template -o ./locale/test.po -L Vue`

It will find all `.vue` in the `./src/components` directory, and those files will be the input for the `xgettext-template` command.

Also if you want something more, you could take a look at a module I've been building specifically tailored to Vue.js. It is still in development (no documentation ready), but is very much usable: https://github.com/eldarc/vue-gettext-tools

You can use it like this:
```const { Extractor, Compiler } = require('vue-gettext-tools')

const extractorConfig = {verbose: true}
const compilerConfig = {verbose: true}
const locales = ['en', 'de', 'bs']

Extractor(extractorConfig, ['src/**/*.{vue,js}'], 'locales/po/dictionary.pot')
Compiler(compilerConfig, 'locales/po/dictionary.pot', 'locales/po/', 'locales/json/', locales)```

This will take all files from `src` which are either `.vue` or `.js` and build a `dictionary.pot`. The compiler will take the dictionary and generate `.po` and `.json` files for locales. Also you can specify an array of input directories.

Extractor config options `https://github.com/eldarc/vue-gettext-tools/blob/master/src/extract.js` starting from line 24 in the constant `defaultConfiguration`.

Compiler config options `https://github.com/eldarc/vue-gettext-tools/blob/master/src/compile.js` starting from line 8 in the constant `defaultConfiguration`.

This tool is a helper for this plugin `https://github.com/eldarc/vue-i18n-gettext`. It is also in development, but its planned to have tons of features, like Markdown support, route auto-prefixing, locale switching patterns, automatic detection, etc.

**Comment by chlab** [comment]
Wow, thanks for that great and detailed answer.

I though of using `find` and `xargs` but I wasn't sure if I was maybe misunderstanding the way `xgettext-template` works.

Great work on the vue tools! I usually use `vuex-i18n` and [wrote a little tool](https://github.com/liip-amboss/locale-man) to make creating new texts a bit easier because I wasn't happy with vue-gettext. But what you're working on looks promising!
