### ISSUE TITLE
Support for --sort-output option

### ISSUE THREAD

**Issue by OlivierKamers** [gmarty/xgettext#79]
Hi,

It looks like the gettext-parser used for compiling the PO file supports this option to sort the keys: https://www.npmjs.com/package/gettext-parser#compile-po-from-a-translation-object
The sort option accepts a boolean or a function, but for CLI compatibility this could be limited to the boolean option.

Are you open to accepting a PR for this functionality?

From gettext manual:
> ‘-s’
‘--sort-output’
Generate sorted output. Note that using this option makes it much harder for the translator to understand each message’s context.

**Comment by smhg** [comment]
@OlivierKamers yes, that would be awesome!
