### ISSUE TITLE
Not working when installing in node 12 and above

### ISSUE THREAD

**Issue by misgina** [gmarty/xgettext#81]
Getting this error.
`nunjucks@3.1.3: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <= 11.0.0-0". Got "12.21.0"`

It is fixed in `nunjucks` but `gettext-nunjucks` is using an older version of `nunjucks`.

**Comment by smhg** [comment]
Please report this in the [gettext-nunjucks](https://github.com/eldarc/gettext-nunjucks) repo.
